FROM adoptopenjdk/maven-openjdk11 
COPY . /usr/src/app/image-service
RUN mvn -f /usr/src/app/image-service/pom.xml clean package

EXPOSE 8080

ENTRYPOINT  java -jar /usr/src/app/image-service/target/*.jar