# File resource config
images:
    homePath: ${user.home}/watercolors
    server: ${SERVER:http://localhost:8080}
# Datasource config
spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
    datasource:
        url: jdbc:postgresql://${DB_SERVER}/image-service
        username: dbadmin
        password: watercolors
        initialization-mode: always
    servlet:
        multipart:
            maxFileSize: 1000MB
            maxRequestSize: 1000MB