# Datasource config
spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
    datasource:
        url: jdbc:postgresql://${DB_SERVER}/catalogue
        username: dbadmin
        password: watercolors
        initialization-mode: always
