server:
    port: 8070

spring:

# General
    application:
        name: watercolors-images

# MVC
    mvc:
        servlet:
             path: /api/v1/images

# Datasource config
    jpa:
        properties:
            hibernate:
                default_schema: images
    datasource:
        url: jdbc:postgresql://${DB_SERVER:watercolors-postgres}/${POSTGRES_DB:watercolors}
        username: ${POSTGRES_USER:dbadmin}
        password: ${POSTGRES_PASSWORD:watercolors}
    liquibase:
        default-schema: images
    servlet:
        multipart:
            maxFileSize: 1000MB
            maxRequestSize: 1000MB

# Kubernetes config
    cloud:
        kubernetes:
            discovery:
                all-namespaces: true

# File resource config
images:
    homePath: ${user.home}/watercolors
    server: ${SERVER:http://localhost:8080}
    resizeWidth: 500
            
# Monitoring
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"