# Datasource config
spring:
    application:
        name: watercolors-catalogue
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:postgresql://${DB_SERVER:watercolors-postgres}/${POSTGRES_DB:watercolors}
        username: ${POSTGRES_USER:dbadmin}
        password: ${POSTGRES_PASSWORD:watercolors}
        initialization-mode: always
    cloud:
        kubernetes:
            discovery:
                all-namespaces: true
