kind: PersistentVolume
apiVersion: v1
metadata:
  name: images-pv-volume
  labels:
    type: local
    app: watercolors-images
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/watercolors"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: images-pv-claim
  labels:
    app: watercolors-images
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi